# numpay packages
1.numerics
2.computation

In [1]:
import numpy as np

In [2]:
#1-dimensional array
a=np.array([1,2,3,4,5])
print(a)
a.ndim


[1 2 3 4 5]


1

In [3]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
a1.ndim


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [4]:
a1.shape

(3, 3)

In [5]:
a.shape

(5,)

In [12]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.shape[0])#rows
print(a2.shape[1])#columns


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4
3


In [13]:
a3=np.array([],dtype="int32")


In [5]:
import numpy as np
a3=np.append(a3,int(input()))
a3

12


array([12])

In [6]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([12, 23, 34, 45, 56, 67])

# slicing

In [8]:
print(a3[3])

45


In [14]:
print(a2[2:,:])


[[ 7  8  9]
 [10 11 12]]


In [15]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [16]:
print(a2[0,0:2])


[1 2]


In [17]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


# ilterate through array

In [18]:
for row in a2:
    print(row)


[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [19]:
list1=[[1,2],[3,4]]
for i in list1:
    print(i)


[1, 2]
[3, 4]


In [20]:
for ele in a2.flat:
    print(ele,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 

In [21]:
np.array(a2.flat)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# indexing with boolean array

In [22]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [23]:
result=(arr1%2==0)
result



array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [24]:
arr1[result]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
# appending array


In [26]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2))) #vertical stacking


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [27]:
print(np.hstack((arr1,arr2))) #horizontal stacking


[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
Attributes:
size
itemsize
dtype
ndim
shape


In [30]:
arr=np.arange(1,11).reshape(2,5)
arrprint(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
Functions:
zeros()
ones()
full()
eye()
linspace()
arange()
reshape()
ravel()

In [31]:
z=np.zeros((2,3),dtype="int32")
z


array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
f=np.full((2,2),"shraavya")
print(f)


[['shraavya' 'shraavya']
 ['shraavya' 'shraavya']]


In [34]:
#eye()
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
#linspace() -->linear spacing elements will return
l=np.linspace(1,10,5) #1-10 are divided into 5 equal parts
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
a=np.arange(1,13,2)# range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [37]:
print(a.shape) # 6 elements
a=a.reshape(2,3)
a

(6,)


array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [38]:
#ravell() --> flattens your array elements
print(np.array(a.flat))
print(a.ravel())


[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


In [ ]:
Function:
min()
max()
sum()
sqrt()
mean()
median()
std()

In [39]:
print(a.min())
print(a.max())


1
11


In [41]:
a


array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [42]:
print(a.sum())# sum of all the elements
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of column elements


36
[ 9 27]
[ 8 12 16]


In [43]:
np.sqrt(a)


array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [44]:
np.mean(a)


6.0

In [45]:
np.median(a)

6.0

In [46]:
np.std(a)

3.415650255319866

In [47]:
# mathematical operations:

In [48]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# dot->matrix multpilication
# arr1= m*n
# arr2=n*1

In [50]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)
arr1

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [51]:
arr1#Transpose of an array
arr1.T


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#Transpose of an array
arr1.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# applying user-defined functions:

In [53]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
#1/(1+1)-->x/(x+1)
r=[x/(x+1) for x in list1] 
r

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [56]:
f=np.vectorize(lambda x:x/(x+1))
f(a)


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])