In [37]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1


71
0.010289858138154195


In [38]:
#creating an array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))


[52 75 18]
[[44 63 76 16]
 [46 55 50 80]
 [ 8 92 72 39]]
[[[69  5]
  [98 18]
  [42 63]
  [95 83]]

 [[93 52]
  [32 29]
  [ 4 86]
  [42 76]]

 [[67 14]
  [ 4 81]
  [19  0]
  [57 55]]]


In [39]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))


0.9328809612424726
[0.22000502 0.13841725 0.84330315]
[[0.73655948 0.56077473 0.93258452]
 [0.66477716 0.62954194 0.24318801]]


In [40]:
a=random.randint(100,size=(3,2)).ravel()
a#single element will be selected
random.choice(a)


array([83, 30, 36, 79, 90, 83])

In [41]:
#single element will be selected
random.choice(a)


83

In [42]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))


array([[3, 5, 2, 4],
       [4, 4, 5, 1],
       [4, 5, 4, 1]])

# pandas 
1. data manupulation
2. tabular,unlabelled

In [ ]:
###creating a dataframe
1.using 2 dictionaries

In [2]:
import pandas as pd
import numpy as np
dict1 = {'a' : 1,'b':2,'c':3,'d' : 4,'e':5}
dict2 = {'a' : 5,'b':6,'c':7,'d' : 8,'e':9}
data = {"First":dict1,"second":dict2}
df=pd.DataFrame(data,dtype =np.int32)
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [3]:
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [4]:
#simple dictionary --> dataframe
d1={"name" : ["shraavya","kunch","ganesh"],"address":["hyd","adb","AP"]}
pd.DataFrame(d1)


name address
0  shraavya     hyd
1     kunch     adb
2    ganesh      AP

In [11]:
#using Series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.24,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3" :s3}
df3 = pd.DataFrame(data)
df3


column1  column2 column3
0        1    12.23       a
1        2    23.24       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

# selecting the data from the data frame:
1. loc
2. iloc

In [20]:
type(df3)

pandas.core.frame.DataFrame

In [12]:
df3["column2"]

0    12.23
1    23.24
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [15]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.24       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [17]:

df3.loc[:,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.24
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78
6        7    34.45
7        8    23.34
8        9    67.40
9       10    23.00

In [18]:
#single coloumn
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [22]:
#extracting multiple colunm values:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.24
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [23]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [24]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### retrieving the information of dataframe:

In [25]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 264.0+ bytes


In [26]:
df3.shape

(10, 3)

In [27]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [28]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
### viewing data from dataframe:
1.head()
2.tail()
3.sample()

In [29]:
df3.head() #first 5 values

column1  column2 column3
0        1    12.23       a
1        2    23.24       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [30]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.24       b
2        3    45.30       c

In [31]:
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [32]:
df.tail(2)

First  second
d      4       8
e      5       9

In [33]:
df3.sample(2)

column1  column2 column3
4        5    67.40       e
6        7    34.45       g

In [34]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.964000
std     3.02765  21.007205
min     1.00000  12.230000
25%     3.25000  23.265000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [36]:
#renaming the column headers
df3.rename(columns={"column1":"first",
                    "column2": "second",
                     "column3":"third"})
df3

column1  column2 column3
0        1    12.23       a
1        2    23.24       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j