In [8]:
import string
from random import *
print("welcome password picker !!!")
adj = ["excellent" ,"very good" ,"good" ,"bad" ,"poor"]
noun = ["shraavya", " kunch", " spoorthi","roopa"]
digits = string.digits
spl_char = string.punctuation


welcome password picker !!!


In [9]:
while True:
    password = choice(adj) + choice(noun) + choice(digits) + choice(spl_char)
    print("your password is : ", password)
    print("do you want to generate the new password? ")
    response=input("enter yes for new password and NO for not generating the password")
    if response == "NO":
        break
    elif response == "yes":
            continue
    else:
                print("enter either yes or NO")

your password is :  goodshraavya3$
do you want to generate the new password? 
enter yes for new password and NO for not generating the passwordyes
your password is :  very goodshraavya2{
do you want to generate the new password? 
enter yes for new password and NO for not generating the passwordNO


### module:
1. pre defined module
2. user defined modules

In [10]:
import string
string.digits

'0123456789'

In [11]:
import string as s
s.digits

'0123456789'

In [15]:
from string import digits,punctuation 
digits = 10
print(digits)
print(punctuation)


10
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [16]:
from string import * 

In [18]:
list1 = [1,2,3,4,5]
sum = 0
for i in list1:
    sum+= i
print(sum)

15


#user defined modules:

In [1]:
import operations as o
o.wish("shraavya")

good afternoon shraavya


###build in libararies 

1.math

In [7]:
import math
help("math")

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.
   

In [8]:
math.factorial(5)

120

In [12]:
#using math module find out area of a circle(pi*r*r)
def area(radius):
    return math.pi * radius * radius
area(7)

153.93804002589985

In [13]:
import statistics as s
list1 = list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [14]:
print(s.mean(list1))
print(sum(list1)/len(list1))

10.5
10.5


In [15]:
print(s.median(list1))

10.5


In [17]:
list2 = [1,2,3,4,3,3,4]
print(s.mode(list2))

3


In [18]:
s.stdev(list2)

1.0690449676496976

In [20]:
s.variance(list2)

1.1428571428571428

###random :
1. randint() ---> randint(start,stop),start abd stops values are included
2. randrange()----> stop value is exlcuded
3. random()---. 0-1
4. choice()--- gives u single element
5. choices()--- gives you multiple elements



In [23]:
import random
print(random.randint(1,10))
print(random.randrange(1,10))
print(random.random())

2
9
0.004428502365877107


In [26]:
list1 = [1,2,3,4,5,6,7,8]
print(random.choice(list1))
print(random.choices(list1,k = 3))

8
[1, 4, 5]


In [ ]:
#os 


In [ ]:
os:
remove() --> removing
rename() -->renaming
mkdir() --> make a directory
getcwd() --> get current working directory
listdir() -->gives you list of things
chdir() --> change directory
rmdir() -->removing the directory


In [31]:
import os
os.mkdir("sample")


In [32]:
os.getcwd()

'C:\\Users\\Ganesh'

In [33]:
os.listdir()


['(01-06-2020)-worklog.ipynb',
 '.conda',
 '.condarc',
 '.config',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.spyder-py3',
 '03-06-2020.ipynb',
 '28-05-2020.ipynb',
 '29-05-2020.ipynb',
 '30-05-2020(worklog).ipynb',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'assignment(01-06-2020).ipynb',
 'assignment(02-06-2020).ipynb',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d0930ad0-e606-11e9-8a50-ce78164a040b}.TM.blf',
 'NTUSER.DAT{d0930ad0-e606-11e9-8a50-ce78164a040b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d0930ad0-e606-11e9-8a50-ce78164a040b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'operations.py',
 'Pictures',
 'PrintHood',
 'Recent',
 'sample',
 'sample.txt',
 'sample1.txt'

In [34]:
os.rmdir("sample")

# # numpy packages

In [ ]:
operations related to numerics
Computational operations


In [35]:
import numpy as np
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)
type(arr1)


[1 2 3 4 5]


numpy.ndarray

In [36]:
list2=list(range(1,11))
list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Difference between python list and numpy array¶
Less memory compare to python list
Fast
convenient than python list


In [39]:
import sys
size=1000
list1= list(range(size))
print(sys.getsizeof(list1[0])*size)
arr1=np.arange(1000)
print(arr1.itemsize*arr1.size)


12000
4000


In [43]:
import time
size=20000
list1=list(range(size))
list2=list(range(size))
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print("time took for python list:",time.time()-start)
arr1=np.arange(size)
arr2=np.arange(size)
start=time.time()
result=arr1+arr2
print("time took for numpy array:",time.time()-start)


time took for python list: 0.0
time took for numpy array: 0.0009987354278564453


In [41]:
l1=[1,2,3,4,5]
l2=[10,11,12,23,14]
#result=[11,13,15,27,19]
result=[x+y for x,y in zip(l1,l2)]
result


[11, 13, 15, 27, 19]

In [42]:
a1=np.array(l1)
a2=np.array(l2)
a1+a2


array([11, 13, 15, 27, 19])